name: Daily Inventory Scraper

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List files
      run: ls -la

    - name: Wait 1 second
      run: sleep 1

    - name: Run scraper
      run: python script.py

    - name: Show inventory.json
      run: cat inventory.json

    - name: Commit and push files
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add inventory_data.csv inventory_data_UK.csv inventory.json urls.json max_inventory.json
        git commit -m 'Update inventory files'
        git push
      continue-on-error: true