name: Get Product Links from Mattel (2x per day)

# on:
#   schedule:
#     - cron: '0 1,13 * * *'  # Запуск о 01:00 та 13:00 UTC щодня
#   workflow_dispatch:  # Дозволяє ручний запуск

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Pull latest changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git pull origin main --rebase
      continue-on-error: true

    - name: Run scraper
      run: python scrape_mattel.py

    - name: Debug git status
      run: |
        git status
        git diff
      continue-on-error: true

    - name: Pull latest changes before commit
      run: |
        git pull origin main --rebase
      continue-on-error: true

    - name: Commit and push files
      run: |
        git add urls.json
        git commit -m 'Update links to products' || echo "No changes to commit"
        git push origin main
      continue-on-error: true
