name: Scrape Mattel Creations

on:
  schedule:
    - cron: '0 1,13 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 playwright
        playwright install

    - name: Run scraper
      run: python scrape_mattel.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: mattel-products
        path: urls.json