name: Get Qty from Mattel (each 4h)

on:
  schedule:
    - cron: '0 2,6,10,12,18,22 * * *'  # Кожні 4 години, включаючи 16:00 UTC
  workflow_dispatch:  # Дозволяє ручний запуск

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pull latest changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git pull origin main --rebase
      continue-on-error: true

    - name: Run scraper
      run: python script.py

    - name: Commit and push files
      run: |
        git add docs/inventory.json max_inventory.json
        git commit -m 'Update inventory files' || echo "No changes to commit"
        git push origin main
      continue-on-error: true